version: '3'

services:
  pg:
    image: postgres
    environment:
      - POSTGRES_DB=mydictionary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: DevelopmentConfig
      SQLALCHEMY_DATABASE_URI: postgresql+pg8000://postgres:password@pg/mydictionary
    depends_on:
      - pg
    ports:
      - "5001:5000"

  app-prod:
    build:
      context: .
      dockerfile: docker-build/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+pg8000://postgres:password@pg/mydictionary
    ports:
      - "5080:80"
    depends_on:
      - pg
volumes:
  pg-data: